### ISSUE TITLE
Hosted  version of the demo does not work

### ISSUE THREAD

**Issue by vanvuongngo** [SkalyIO/Freighter#1]
Hosted version of the demo https://freighter.skaly.io/ does not work.
Link is on the demo https://github.com/SkalyIO/Freighter/blob/265553062a1d08f19787176af542d55b744a09c3/Demo/README.md

Nginx shows an error message: `404 Not Found`

**Comment by peterwilli** [comment]
> Hosted version of the demo https://freighter.skaly.io/ does not work.
> Link is on the demo https://github.com/SkalyIO/Freighter/blob/265553062a1d08f19787176af542d55b744a09c3/Demo/README.md
> 
> Nginx shows an error message: `404 Not Found`

Hey there, thank you for telling me. I was moving servers and forgot to bring back up the VM to the new drive. All is good again.!
